
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 10 23:06:55 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 50;
  public static final int CONST = 48;
  public static final int CHAR = 17;
  public static final int GE = 25;
  public static final int CONTINUE = 39;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 12;
  public static final int STAR = 28;
  public static final int RPAREN = 7;
  public static final int RECORD = 49;
  public static final int DMINUS = 47;
  public static final int LS = 26;
  public static final int BOOL = 18;
  public static final int COMMA = 8;
  public static final int CLASS = 32;
  public static final int DIV = 29;
  public static final int PLUS = 11;
  public static final int IF = 19;
  public static final int THIS = 40;
  public static final int DOT = 43;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int LAND = 44;
  public static final int RETURN = 10;
  public static final int RBRACKET = 51;
  public static final int EQUAL = 13;
  public static final int SUPER = 41;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int LOR = 45;
  public static final int DEQUAL = 22;
  public static final int NUMBER = 15;
  public static final int BREAK = 31;
  public static final int IDENT = 16;
  public static final int VOID = 14;
  public static final int COLON = 21;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int READ = 37;
  public static final int ENUM = 33;
  public static final int GOTO = 42;
  public static final int WHILE = 35;
  public static final int NEQUAL = 23;
  public static final int RBRACE = 4;
  public static final int DPLUS = 46;
  public static final int EXTENDS = 38;
  public static final int PROG = 2;
  public static final int PROC = 30;
  public static final int GR = 24;
  public static final int PRINT = 9;
  public static final int DO = 34;
}

